name: JourneyCitizens
version: '${version}'
main: net.whimxiqal.journey.integration.citizens.JourneyCitizens
api-version: 1.17
depend: [ Journey, Citizens ]
authors: [ whimxiqal ]
description: Integrates Journey with Citizens
