name: JourneyNotQuests
version: '${version}'
main: net.whimxiqal.journey.integration.notquests.JourneyNotQuests
api-version: 1.21
depend: [ Journey, NotQuests ]
authors: [ whimxiqal ]
description: Integrates Journey with NotQuests
