name: Journey
version: ${version}
main: net.whimxiqal.journey.bukkit.JourneyBukkit
api-version: 1.17
authors:
  - whimxiqal
description: A path-optimization Minecraft solution
website: https://github.com/whimxiqal/journey
