name: JourneyBetonQuest
version: '${version}'
main: net.whimxiqal.journey.integration.betonquest.JourneyBetonQuest
api-version: 1.17
depend: [ Journey, BetonQuest ]
authors: [ whimxiqal ]
description: Integrates Journey with BetonQuest
