name: Continuous Integration

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'
      - 'release/*'
      - 'feature/*'

jobs:
  gradle_validation:
    name: Gradle Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validate
        uses: gradle/actions/wrapper-validation@v3

  build:
    name: Build and Upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get all tags
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Set Production Build Environment
        if: github.ref == 'refs/heads/main' || github.ref_type == 'tag'
        shell: bash
        run: echo "JOURNEY_ENV=PROD" >> $GITHUB_ENV
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build with Gradle
        run: ./gradlew build
      - name: Move Artifacts to Root
        shell: bash
        run: cp $(find ./ -wholename '*/build/libs/*.jar') ./
      - name: Upload all artifacts
        uses: actions/upload-artifact@v4
        with:
          name: journey-artifacts
          path: |
            Journey-Bukkit-*.jar
            JourneyCitizens-*.jar
            JourneyEssentials-*.jar
            JourneyNotQuests-*.jar
            JourneyBetonQuest-*.jar
