name: Continuous Integration

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'
      - 'release/*'
      - 'feature/*'
      - 'develop'
jobs:
  gradle_validation:
    name: Gradle Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Validate
        uses: gradle/wrapper-validation-action@v1

  checkstyle:
    name: Checkstyle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run check style
        uses: nikitasavinov/checkstyle-action@master
        with:
          fail_on_error: true
          reporter: 'github-pr-check'
          tool_name: 'checkstyle'
          level: error
          filter_mode: nofilter
          checkstyle_config: checkstyle.xml
          checkstyle_version: 9.0.1

  build:
    name: Build and Upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 16
        uses: actions/setup-java@v3
        with:
          java-version: '16'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload all artifacts
        uses: actions/upload-artifact@v3
        with:
          name: jars
          path: |
            bukkit/build/libs/Journey-Bukkit-*.jar
