name: Gradle Validation

on: [pull_request]

jobs:
  gradle_validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Validate
        uses: gradle/wrapper-validation-action@v1